project:
  type: website

website:
  title: "Eva's Data Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Projects"
        menu:
          - text: "Project 1"
            href: scorecard_analysis.html
          - text: "Project 2"
            href: WCA_analysis.html
          - text: "Project 3"
            href: mapping.html
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css


